allow single word host names
logstash-plugins/logstash-mixin-validator_support pull request #7
Opened 2023-11-10 15:46 UTC by jsvd

fixes #6

2023-11-10 18:38 UTC, yaauie commented on lib/logstash/plugin_mixins/validator_support/required_host_optional_port_validation_adapter.rb
> +      is_valid_hostname = ->(candidate) { (%r{\A([a-z0-9]+(-[a-z0-9]+)*\.)?[a-z]{2,}\Z}i).match?(candidate) }
This pattern feels a bit arbitrary, both too lax (`this..that` passes but should fail) and not enough (`asd-f` fails, but should pass).

I wrote and [validated](https://regexr.com/7n2ce) an RFC1123-compliant expression that enforces the format of the labels, the label max lengths, and the whole hostname max length, all without wildcards that could lead to backtracking issues:

```suggestion
      # RFC1123 validated at https://regexr.com/7n2ce
      rfc1123_hostname_pattern = %r{\A(?=.{1,255}\z)(?:(?=[^.]{1,63}(?:[.]|\z))[a-z0-9]+(?:[a-z0-9\-]+[a-z0-9])?(?:[.]|\z))+\z}i
      is_valid_hostname = ->(candidate) { rfc1123_hostname_pattern.match?(candidate) }
```

2023-11-13 18:38 UTC, yaauie requested changes
Needs changelog + version bump -> https://github.com/jsvd/logstash-mixin-validator_support/pull/1

2023-11-13 18:46 UTC, jsvd commented
@logstashmachine bump patch

2023-11-13 19:49 UTC, yaauie approved these changes
LGTM 👍🏼

2023-11-24 10:08 UTC, merged